
const fs=require("fs"),vm=require("vm"),assert=require("assert/strict");
const data=new Map();
const localStorage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k),key:i=>[...data.keys()][i],get length(){return data.size}};
function context(){
 const ctx=vm.createContext({localStorage,console,setTimeout:fn=>{fn();return 0},URLSearchParams,window:{location:{pathname:"/index.html",replace(){}},addEventListener(){}}});
 vm.runInContext(fs.readFileSync("js/api.js","utf8")+"\nthis.app={sesion,auth,usuarios,cursos,evaluaciones,progreso,lecciones,solicitudesReset,DB,dbListaPromise};",ctx);
 return ctx.app;
}
(async()=>{
 let a=context();await a.dbListaPromise;
 const login=async name=>{const r=await a.auth.login(name,name==="ana"?"Admin2026":"Test2026");a.sesion.guardar(r.token,r.usuario)};
 await login("ana");assert.equal(a.sesion.rol(),"superadmin");
 const admin=await a.usuarios.crear({nombre:"Admin",correo:"admin@test.mx",password:"Test2026",rol:"admin"});
 const instructor=await a.usuarios.crear({nombre:"Instructor",correo:"instructor@test.mx",password:"Test2026",rol:"instructor"});
 const worker=await a.usuarios.crear({nombre:"Worker",correo:"worker@test.mx",password:"Test2026",rol:"trabajador"});
 await assert.rejects(a.usuarios.cambiarEstado(a.sesion.usuario().id,false));
 await login("instructor@test.mx");
 assert.equal(a.sesion.activa(),true);
 await assert.rejects(a.usuarios.listar());await assert.rejects(a.solicitudesReset.listar());
 const course=await a.cursos.crear({nombre:"Prueba",modulos:[]});assert.equal(course.estado,"pendiente");assert.equal(course.asignadoA,"");
 await assert.rejects(a.cursos.cambiarEstado(course.id,"publicado"));
 await assert.rejects(a.cursos.asignar(course.id,{asignadoA:"Todos"}));
 await assert.rejects(a.cursos.actualizar(course.id,{estado:"publicado"}));
 await login("admin@test.mx");
 await assert.rejects(a.cursos.crear({nombre:"Prohibido"}));
 await assert.rejects(a.cursos.actualizar(course.id,{nombre:"Prohibido"}));
 await assert.rejects(a.usuarios.cambiarPassword(worker.id,"X"));
 await assert.rejects(a.usuarios.cambiarEstado(admin.id,false));
 await assert.rejects(a.usuarios.crear({nombre:"Elevado",correo:"e@test.mx",password:"x",rol:"superadmin"}));
 await assert.rejects(a.usuarios.cambiarRol(worker.id,"admin"));
 assert.ok((await a.usuarios.listar()).every(u=>!("password" in u)));
 await a.cursos.cambiarEstado(course.id,"publicado");
 await a.cursos.asignar(course.id,{asignadoAIds:[worker.id]});
 await login("worker@test.mx");
 assert.equal((await a.cursos.obtener(course.id)).estado,"publicado");
 await assert.rejects(a.usuarios.listar());await assert.rejects(a.cursos.cambiarEstado(course.id,"publicado"));
 await login("instructor@test.mx");await a.cursos.actualizar(course.id,{nombre:"Actualizado"});
 await login("worker@test.mx");await assert.rejects(a.cursos.obtener(course.id));
 await login("admin@test.mx");await a.cursos.cambiarEstado(course.id,"publicado");
 await a.cursos.asignar(course.id,{asignadoAIds:[]});
 await login("worker@test.mx");await assert.rejects(a.cursos.obtener(course.id));
 await login("instructor@test.mx");await a.evaluaciones.actualizarTipo(course.id,"examen",{preguntas:[]});
 assert.equal((await a.cursos.obtener(course.id)).estado,"pendiente");
 a=context();await a.dbListaPromise;
 await login("admin@test.mx");
 assert.equal((await a.cursos.obtener(course.id)).estado,"pendiente");
 assert.equal((await a.cursos.obtener(course.id)).asignadoA,"");
 await a.usuarios.cambiarEstado(worker.id,false);await assert.rejects(login("worker@test.mx"));
 await login("ana");await a.usuarios.cambiarPassword(admin.id,"Changed2026");await a.usuarios.cambiarEstado(admin.id,false);
 assert.ok((await a.usuarios.listar()).find(u=>u.id===admin.id).activo===false);
 await login("ana");
 await a.usuarios.cambiarEstado(worker.id,true);
 await login("worker@test.mx");
 const persisted=JSON.parse(localStorage.getItem("cicsa_usuarios"));
 persisted.find(u=>u.id===worker.id).activo=false;
 localStorage.setItem("cicsa_usuarios",JSON.stringify(persisted));
 await assert.rejects(a.cursos.listar());
 await login("ana");
 await login("instructor@test.mx");
 const changed=JSON.parse(localStorage.getItem("cicsa_usuarios"));
 changed.find(u=>u.id===instructor.id).rol="trabajador";
 localStorage.setItem("cicsa_usuarios",JSON.stringify(changed));
 await assert.rejects(a.cursos.crear({nombre:"Stale role"}));
 assert.equal(a.sesion.rol(),"trabajador");
 console.log("PASS: four roles, protected administration, approval, assignments, content access, persistence, deactivation and password management.");
})().catch(e=>{console.error(e);process.exitCode=1});
