
const fs = require("fs"), vm = require("vm"), assert = require("assert/strict");
const data = new Map();
const localStorage = {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k),key:i=>[...data.keys()][i],get length(){return data.size}};
const ctx=vm.createContext({localStorage,console,setTimeout:f=>f(),URLSearchParams,window:{location:{pathname:"/index.html",replace(){}},addEventListener(){}}});
vm.runInContext(fs.readFileSync("js/api.js","utf8")+"\nthis.app={auth,sesion,soporte,usuarios,dbListaPromise};",ctx);
(async()=>{
 const a=ctx.app;await a.dbListaPromise;
 const login=async(name,password)=>{const r=await a.auth.login(name,password);a.sesion.guardar(r.token,r.usuario);};
 await login("jhovany","Cicsa2026");
 const general=await a.soporte.crear({tipo:"curso",descripcion:"No se reproduce el video del curso.",usuarioId:999,nombre:"Falso",estado:"resuelto"});
 assert.equal(general.usuarioId,a.sesion.usuario().id);assert.equal(general.estado,"pendiente");assert.notEqual(general.nombre,"Falso");
 const password=await a.soporte.crear({tipo:"password",descripcion:"Necesito restablecer mi contraseña."});
 await assert.rejects(a.soporte.actualizar(general.id,{estado:"resuelto",respuesta:"Manipulado"}));
 await assert.rejects(a.soporte.crear({tipo:"otro",descripcion:"Problema con una captura",captura:"data:text/html;base64,AAAA"}));
 await assert.rejects(a.soporte.crear({tipo:"repetir",descripcion:"Quiero volver a realizar un curso."}));
 await assert.rejects(a.soporte.crear({tipo:"curso",cursoId:99999,descripcion:"Curso que no está asignado."}));
 await login("instructor","Instructor2026");
 assert.equal((await a.soporte.listar()).length,0);
 await assert.rejects(a.soporte.actualizar(general.id,{estado:"resuelto",respuesta:"Sin permiso"}));
 const inst=await a.soporte.crear({tipo:"otro",descripcion:"Necesito ayuda con el editor de cursos."});
 await login("administrador","AdminDemo2026");
 const adminTickets=await a.soporte.listar();
 assert.ok(adminTickets.some(t=>t.id===general.id && t.puedeAtender));
 assert.ok(adminTickets.some(t=>t.id===inst.id && t.puedeAtender));
 assert.ok(!adminTickets.some(t=>t.id===password.id));
 await assert.rejects(a.soporte.actualizar(password.id,{estado:"resuelto",respuesta:"No autorizado"}));
 await assert.rejects(a.soporte.actualizar(general.id,{estado:"resuelto",respuesta:""}));
 await a.soporte.actualizar(general.id,{estado:"en_atencion",respuesta:"Estamos revisando el video."});
 const adminOwn=await a.soporte.crear({tipo:"acceso",descripcion:"Tengo un problema con mi cuenta administrativa."});
 assert.equal(adminOwn.soloSuperadmin,true);assert.equal(adminOwn.puedeAtender,false);
 await login("ana","Admin2026");
 assert.ok((await a.soporte.listar()).some(t=>t.id===password.id && t.puedeAtender));
 assert.ok((await a.soporte.listar()).some(t=>t.id===adminOwn.id && t.puedeAtender));
 await a.soporte.actualizar(general.id,{estado:"resuelto",respuesta:"El video ya está disponible."});
 await login("jhovany","Cicsa2026");
 const own=await a.soporte.listar();assert.equal(own.length,2);assert.ok(own.every(t=>!t.puedeAtender));
 assert.equal(own.find(t=>t.id===general.id).respuesta,"El video ya está disponible.");
 assert.equal(JSON.parse(data.get("cicsa_soporte")).length,4);
 console.log("PASS: identity from session, own-ticket privacy, admin/superadmin routing, instructor restrictions, attachment validation, required resolution and persistence.");
})().catch(e=>{console.error(e);process.exitCode=1});
